name: unit-test
description: "Run unit tests for GdUnit3 API"

inputs:
  test-includes:
    description: "Paths to include for test run"
    required: true

runs:
  using: composite
  steps:
    - name: "Unit Test"
      env:
        GODOT_BIN: "/usr/local/bin/godot"
      shell: bash
      run: ./runtest.sh --add ${{ inputs.test-includes }} --continue
   