name: unit-test
description: "Runs the Unit Tests on GdUnit3 API"

inputs:
  test-includes:
    description: "The path to include tests to be run"
    required: true
  godot-bin:
    required: true

runs:
  using: composite

  steps:
    - name: "Unit Test Linux"
      if: ${{ runner.OS == 'Linux' }}
      env:
        GODOT_BIN: "/home/runner/godot-linux/godot"
      shell: bash
      run: |
        chmod +x ./addons/gdUnit3/runtest.sh
        xvfb-run --auto-servernum ./addons/gdUnit3/runtest.sh --add ${{ inputs.test-includes }} --continue --audio-driver Dummy --verbose
