name: install-godot-image
description: "Installs the Godot image"

inputs:
  godot-version:
    description: "The Godot Engine version to run"
    required: true

runs:
  using: composite
  steps:
    - name: Install Godot ${{ inputs.godot-version }}
      continue-on-error: false
      container:
        image: barichello/godot-ci:${{ inputs.godot-version }}