name: ci-dev

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.yml'
      - '**.jpg'
      - '**.png'
      - '**.md'
  workflow_dispatch:

env:
  GODOT_BIN: "/usr/local/bin/godot"

concurrency:
  group: ci-dev-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  testing:
    strategy:
      matrix:
        godot-version: [3.5.1]

    name: "CI Godot ${{ matrix.godot-version }}"
    runs-on: ubuntu-latest
    timeout-minutes: 12
    continue-on-error: true
    container:
      image: barichello/godot-ci:${{ matrix.godot-version }}

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: 'recursive'

      - name: "Update Project"
        if: ${{ !cancelled() }}
        timeout-minutes: 1
        continue-on-error: true # we still ignore the timeout, the script is not quit and we run into a timeout
        run: |
          ${{ env.GODOT_BIN }} -e --path . -s res://addons/gdUnit3/src/core/scan_project.gd --no-window

      - name: "Run Unit Test"
        if: ${{ !cancelled() }}
        timeout-minutes: 10
        uses: ./.github/actions/unit-test
        with:
          godot-bin: ${{ env.GODOT_BIN }}
          test-includes: "res://addons/gdUnit3/test/"

      - name: "Publish Unit Test Reports"
        if: ${{ !cancelled() }}
        uses: ./.github/actions/publish-test-report
        with:
          report-name: ${{ matrix.godot-version }}

      - name: "Upload Unit Test Reports"
        if: ${{ !cancelled() }}
        uses: ./.github/actions/upload-test-report
        with:
          report-name: ${{ matrix.godot-version }}
