name: ci-pr
run-name: ${{ github.head_ref || github.ref_name }}-ci-pr

on:
  pull_request:
    paths-ignore:
      - '**.yml'
      - '**.jpg'
      - '**.png'
      - '**.md'
  workflow_dispatch:


concurrency:
  group: ci-pr-${{ github.event.number }}
  cancel-in-progress: true


jobs:
  unit-tests:
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        godot-version: [3.4.1, 3.4.2, 3.4.4, 3.4.5, 3.5, 3.5.1, 3.5.2]

    name: "Unit tests on Godot 🐧 v${{ matrix.godot-version }}"
    uses: ./.github/workflows/unit-tests.yml
    with: 
      godot-version: ${{ matrix.godot-version }}
      godot-mono: false

    name: "Unit tests on Godot 🐧 Mono v${{ matrix.godot-version }}"
    uses: ./.github/workflows/unit-tests.yml
    with:
      godot-version: ${{ matrix.godot-version }}
      godot-mono: true
