name: ci-pr

on:
  pull_request:
    paths-ignore:
      - '**.jpg'
      - '**.png'
      - '**.md'
  pull_request_target:
    paths-ignore:
      - '**.jpg'
      - '**.png'
      - '**.md'
  workflow_dispatch:

env:
  GODOT_BIN: "/usr/local/bin/godot"

concurrency:
  group: ci-pr-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  gd-uint-test:
    strategy:
      fail-fast: false
      matrix:
        godot-version: [3.4.1, 3.4.2, 3.4.4]

    name: "CI Godot ${{ matrix.godot-version }}"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    continue-on-error: false
    container:
      image: barichello/godot-ci:${{ matrix.godot-version }}

    steps:
      - name: "Checkout"
        if: ${{ !cancelled() }}
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: 'recursive'

      - name: "Update Project"
        if: ${{ !cancelled() }}
        timeout-minutes: 3
        run: |
          ${{ env.GODOT_BIN }} -e --path . res://addons/gdUnit3/scan_project.tscn --no-window --quiet

      - name: "Unit Test"
        if: ${{ !cancelled() }}
        timeout-minutes: 10
        uses: ./.github/actions/unit-test
        with:
          test-includes: "res://addons/gdUnit3/test/"

      - name: "Unit Test Examples"
        if: ${{ !cancelled() }}
        timeout-minutes: 5
        uses: ./.github/actions/unit-test
        with:
          test-includes: "res://gdUnit3-examples"

      - name: "Publish Unit Test Reports"
        if: ${{ !cancelled() }}
        uses: ./.github/actions/publish-test-report
        with:
          report-name: ${{ matrix.godot-version }}

      - name: "Upload Unit Test Reports"
        if: ${{ !cancelled() }}
        uses: ./.github/actions/upload-test-report
        with:
          report-name: ${{ matrix.godot-version }}

  mono-uint-test:
    strategy:
      fail-fast: false
      matrix:
        godot-version: [mono-3.3.3, mono-3.3.4, mono-3.4.1, mono-3.4.2, mono-3.4.4]

    name: "CI Godot ${{ matrix.godot-version }}"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    continue-on-error: false
    container:
      image: barichello/godot-ci:${{ matrix.godot-version }}

    steps:
      - name: "Checkout"
        if: ${{ !cancelled() }}
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: 'recursive'

      - name: "Setup .NET"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: "Compile"
        run: |
          dotnet restore gdUnit3.csproj
          mkdir -p .mono/assemblies/Debug
          cp /usr/local/bin/GodotSharp/Api/Release/* .mono/assemblies/Debug
          dotnet build -verbosity:m

      - name: "Unit Test"
        if: ${{ !cancelled() }}
        timeout-minutes: 15
        uses: ./.github/actions/unit-test
        with:
          test-includes: "res://addons/gdUnit3/test/"

      - name: "Publish Unit Test Reports"
        if: ${{ !cancelled() }}
        uses: ./.github/actions/publish-test-report
        with:
          report-name: ${{ matrix.godot-version }}

      - name: "Upload Unit Test Reports"
        if: ${{ !cancelled() }}
        uses: ./.github/actions/upload-test-report
        with:
          report-name: ${{ matrix.godot-version }}
