name: ci-pr

on:
  pull_request_target:
    paths-ignore:
      - '**.jpg'
      - '**.png'
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.jpg'
      - '**.png'
      - '**.md'
  workflow_dispatch:

env:
  GODOT_BIN: "/usr/local/bin/godot"

concurrency:
  group: ci-pr-${{ github.event.number }}
  cancel-in-progress: true

jobs:

  unit-test:
    strategy:
      fail-fast: false
      matrix:
        godot-build: ['', 'mono-']
        godot-version: [3.4.1, 3.4.2, 3.4.4]

    name: "CI on Godot ${{ matrix.godot-build }}v${{ matrix.godot-version }}"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    continue-on-error: false
    container:
      image: barichello/godot-ci:${{ matrix.godot-build }}${{ matrix.godot-version }}

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: 'recursive'

      - name: "Update Project"
        if: ${{ !cancelled() }}
        timeout-minutes: 1
        continue-on-error: true # we still ignore the timeout, the script is not quit and we run into a timeout
        run: |
          ${{ env.GODOT_BIN }} -e --path . -s res://addons/gdUnit3/src/core/scan_project.gd --no-window

      - name: "Setup .NET"
        if: ${{ startsWith( matrix.godot-build, 'mono') }} # we only setup .Net for mono versions
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: "Compile C#"
        if: ${{ startsWith( matrix.godot-build, 'mono') }} # we only compile .Net for mono versions
        run: |
          dotnet restore gdUnit3.csproj
          mkdir -p .mono/assemblies/Debug
          cp /usr/local/bin/GodotSharp/Api/Release/* .mono/assemblies/Debug
          dotnet build -verbosity:m

      - name: "Run Unit Test"
        if: ${{ !cancelled() }}
        timeout-minutes: 10
        uses: ./.github/actions/unit-test
        with:
          godot-bin: ${{ env.GODOT_BIN }}
          test-includes: "res://addons/gdUnit3/test/"

      - name: "Run Unit Test Examples"
        if: ${{ !cancelled() }}
        timeout-minutes: 1
        uses: ./.github/actions/unit-test
        with:
          godot-bin: ${{ env.GODOT_BIN }}
          test-includes: "res://gdUnit3-examples"

      - name: "Publish Unit Test Reports"
        if: ${{ !cancelled() }}
        uses: ./.github/actions/publish-test-report
        with:
          report-name: ${{ matrix.godot-build }}${{ matrix.godot-version }}

      - name: "Upload Unit Test Reports"
        if: ${{ !cancelled() }}
        uses: ./.github/actions/upload-test-report
        with:
          report-name: ${{ matrix.godot-build }}${{ matrix.godot-version }}
