name: ci-pr

on:
  pull_request:
    paths-ignore:
      - '**.jpg'
      - '**.png'
      - '**.md'
  pull_request_target:
    paths-ignore:
      - '**.jpg'
      - '**.png'
      - '**.md'
  workflow_dispatch:

concurrency:
  group: ci-pr-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  gd-uint-test:
    strategy:
      fail-fast: false
      matrix:
        godot-version: [3.4.1, 3.4.2, 3.4.4]
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: "Checkout"
        if: ${{ !cancelled() }}
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: 'recursive'

      - name: "Install Godot Image"
        if: ${{ !cancelled() }}
        uses: ./.github/actions/install-godot
        with:
          godot-version: ${{ matrix.godot-version }}

      - name: "Unit Test"
        id: selft-test
        if: ${{ !cancelled() }}
        uses: ./.github/actions/unit-test
        with:
          test-includes: "res://addons/gdUnit3/test/"

      - name: "Publish Unit Test Reports"
        if: ${{ !cancelled() }}
        uses: ./.github/actions/publish-test-report
        with:
          report-name: ${{ matrix.godot-version }}

      - name: "Upload Unit Test Reports"
        if: ${{ !cancelled() }}
        uses: ./.github/actions/upload-test-report
        with:
          report-name: ${{ matrix.godot-version }}
